name: case-stage

services:
  db:
    container_name: case-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: processes
      POSTGRES_USER: master
      POSTGRES_PASSWORD: senha_1234_stage_test
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [app-network]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://master:senha_1234_stage_test@db:5432/processes?schema=public
    ports:
      - 3000:3000
    depends_on:
      - db
    networks: [app-network]

  migrator:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://master:senha_1234_stage_test@db:5432/processes?schema=public
    depends_on:
      - db
    command: ["sh", "-lc", "npx prisma generate && npx prisma migrate dev --name init && npx prisma db seed"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks: [app-network]
    restart: "no"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks: [app-network]


networks:
  app-network:

volumes:
  db_data: